### ISSUE TITLE
Chia VDF programming reference

### ISSUE THREAD

**Issue by hartogss** [Chia-Network/chiavdf#156]
Hi all, 

I'm interested in using Chia's VDF for a non-blockchain project and looking for the API to call the "evaluate" and "verify" functions of the VDF from C++. It's fine if initially the API calls a simpler/slower VDF implementation for now, but I would be happy if later it can be swapped out for a more performant one.

However, I'm quite struggling with the codebase due to seemingly duplicated files and implementations.
Is a concise API + documentation available? I checked the [Chia docs](https://docs.chia.net/), but I found no programming reference for the VDF there.

Please let me know if I should post this question elsewhere. It looked like it didn't belong to the [Chia developer Forum](https://developers.chia.net/) (since I'm not working on Chia itself).

Cheers

**Comment by hoffmang9** [comment]
Have you looked at the Python interface or the tests? Try fastvdf.cpp in the Python bindings directory

**Comment by hartogss** [comment]
Thank you, I'll have a look. I am getting the impression that the files `vdf_*.h` etc. are being abandoned in favor in writing all the logic in files like  `prover_*.h`, `verifier.h`. Is that correct?
