### ISSUE TITLE
BUG: Build fails - CMAKE error Could NOT find GMPXX (missing: GMPXX_LIBRARIES)

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [Chia-Network/chiavdf#72]
[chaivdf-cmake-log.txt](https://github.com/Chia-Network/chiavdf/files/6215520/chaivdf-cmake-log.txt)
I have attempted to build an rpm for a Fedora based system, I am certain to have all stated deps installed but perhaps I am missing something? 

I took a look and test.yaml gave some hints.
$ grep -r lib

.github/workflows/build-aarch64.yml:          && curl -L https://gmplib.org/download/gmp/gmp-6.2.1.tar.lz | lzip -dc | tar x
.github/workflows/build.yml:          && curl -L https://gmplib.org/download/gmp/gmp-6.2.1.tar.lz | tar x --lzip
.github/workflows/build.yml:          && cp src/lib/gmp-patch-6.2.1/longlong.h gmp-6.2.1/
.github/workflows/build.yml:          && cp src/lib/gmp-patch-6.2.1/compat.c gmp-6.2.1/
.github/workflows/build.yml:        CIBW_ENVIRONMENT_WINDOWS: "BUILD_VDF_CLIENT=N SETUPTOOLS_USE_DISTUTILS=stdlib"
.github/workflows/test.yaml:        sudo apt-get install libgmp-dev libboost-python-dev libpython3.8-dev libboost-system-dev build-essential -y
.gitmodules:[submodule "src/lib/pybind11"]
.gitmodules:	path = src/lib/pybind11

Have all which is stated below installed: (also is MPIR needed or just GMP?)

boost-devel
boost-python
boost-system
cmake
gcc
gmp
gmp-devel
lzip
python3dist(pybind11)
python3dist(pytest)
python3dist(setuptools)

build log - 

GMP_INCLUDES=/usr/include
-- Found GMP: /usr/include (Required is at least version "5.1.0") 
GMP_INCLUDES=/usr/include
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find GMPXX (missing: GMPXX_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGMPXX.cmake:33 (find_package_handle_standard_args)
  CMakeLists.txt:18 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/ss/rpmbuild/BUILD/chiavdf-1.0.1/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 266, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 112, in run
    self.build_extension(ext)
  File "setup.py", line 139, in build_extension
    subprocess.check_call(["cmake", ext.sourcedir] + cmake_args, env=env)
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/ss/rpmbuild/BUILD/chiavdf-1.0.1/src', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ss/rpmbuild/BUILD/chiavdf-1.0.1/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
error: Bad exit status from /var/tmp/rpm-tmp.AEsgzl (%build)

This would suggest simply missing a standard Package

**Comment by hoffmang9** [comment]
It appears that your gmp version is too old. MPIR is only used on Windows to replace gmp. If you look in .github/workflows/ you can see that we are downloading and monkey patching the current version of GMP so it supports older CPUs better

**Comment by Chewbakka-Wakka** [comment]
Ok ty, however my installed version is the latest at 6.2.1, certainly above 5.1.0.

$ rpm -q gmp
gmp-6.2.1-2.1.fc35.x86_64

**Comment by Chewbakka-Wakka** [comment]
Any ideas what I may be able to try given my gmp version is the latest?

**Comment by hoffmang9** [comment]
Which version of cmake do you have?

**Comment by Chewbakka-Wakka** [comment]
$ rpm -q cmake
cmake-3.19.7-2.fc35.x86_64 

And perhaps some clues inside this file? [chaivdf-cmake-log.txt](https://github.com/Chia-Network/chiavdf/files/6251298/chaivdf-cmake-log.txt)

**Comment by Chewbakka-Wakka** [comment]
Any further thoughts on this @hoffmang9 as I would like to package all the related Chia components for my distro

**Comment by aqk** [comment]
Hi There @Chewbakka-Wakka . 

Here is the workaround I used:

bash```
diff --git a/src/cmake/FindGMP.cmake b/src/cmake/FindGMP.cmake
index 96d4a55..83f2234 100644
--- a/src/cmake/FindGMP.cmake
+++ b/src/cmake/FindGMP.cmake
@@ -36,7 +36,7 @@ message("GMP_INCLUDES=${GMP_INCLUDES}")
 if(GMP_INCLUDES)
   # Since the GMP version macros may be in a file included by gmp.h of the form
   # gmp-.*[_]?.*.h (e.g., gmp-x86_64.h), we search each of them.
-  file(GLOB GMP_HEADERS "${GMP_INCLUDES}/gmp.h" "${GMP_INCLUDES}/gmp-*.h")
+  file(GLOB GMP_HEADERS "${GMP_INCLUDES}/gmp.h" "${GMP_INCLUDES}/gmp-*.h" "${GMP_INCLUDES}/gmp*.h")
   foreach(gmp_header_filename ${GMP_HEADERS})
     file(READ "${gmp_header_filename}" _gmp_version_header)
     string(REGEX MATCH
@@ -68,6 +68,15 @@ if(GMP_INCLUDES)
   endif()
 endif()

+# XXX aqk fix busted gmp detection
+set (GMP_FIND_VERSION_MAJOR 6)
+set (GMP_FIND_VERSION_MINOR 2)
+set (GMP_FIND_VERSION_PATCH 1)
+  set(GMP_FIND_VERSION
+    "${GMP_FIND_VERSION_MAJOR}.${GMP_FIND_VERSION_MINOR}.${GMP_FIND_VERSION_PATCH}")
+set(GMP_VERSION_OK TRUE)
+# XXX end fix
+
 find_library(GMP_LIBRARIES gmp PATHS $ENV{GMPDIR} ${LIB_INSTALL_DIR})

 include(FindPackageHandleStandardArgs)
```

If that works for you, we can try to make it into a PR together.

Good luck!

**Comment by Chewbakka-Wakka** [comment]
Hi @aqk 
Thanks for that... it appears the issue was fixed I was missing this specific rpm

gmp-c++-devel
