### ISSUE TITLE
Build Fails -  Single module only - No module named 'pybind11_tests' 

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [Chia-Network/chiavdf#81]
If someone can assist would be great, it is just this one module I need to build the RPM for my distro.

_____________________________________________________________________________________________________ ERROR collecting test session ________________________________________________________________________________________________________
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
/usr/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
_deps/pybind11-src-src/tests/conftest.py:19: in <module>
    import pybind11_tests  # noqa: F401
**E   ModuleNotFoundError: No module named 'pybind11_tests'**

$ sudo dnf repoquery --whatprovides 'python3dist(pybind11_tests)'
<blank>

$ sudo dnf repoquery --whatprovides 'python3dist(pybind11)'
python-pybind11-0:2.6.2-2.fc35.x86_64
python3-pybind11-0:2.6.2-1.fc34.x86_64

$ pip show pybind11
Name: pybind11
Version: 2.6.2
Summary: Seamless operability between C++11 and Python
Home-page: https://github.com/pybind/pybind11
Author: Wenzel Jakob
Author-email: wenzel.jakob@epfl.ch
License: BSD
Location: /usr/lib64/python3.8/site-packages
Requires: 
Required-by:

and rpm -  python-pybind11-2.6.2-2.fc35.x86_64 is already installed.

**Comment by Chewbakka-Wakka** [comment]
Same errors in 1.0.2 - anyone able to help?
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
/usr/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
_deps/pybind11-src-src/tests/conftest.py:19: in <module>
    import pybind11_tests  # noqa: F401
E   ModuleNotFoundError: No module named 'pybind11_tests'

**Comment by Chewbakka-Wakka** [comment]
Issue remains...

**Comment by hoffmang9** [comment]
Which cmake3 version do you have?
