### ISSUE TITLE
Maybe we are not the fastest timelord

### ISSUE THREAD

**Issue by losingle** [Chia-Network/chiavdf#82]
logger info :
```
Not skipping peak, don't have. Maybe we are not the fastest timelord
```

Meaning, I don't have to run Timelord myself, right?

**Comment by hoffmang9** [comment]
Yes. Better to run a bluebox if you're not one of the very fastest Timelords.

**Comment by losingle** [comment]
> Yes. Better to run a bluebox if you're not one of the very fastest Timelords.

How to deploy multiple Blueboxes?
I feel like the Bluebox I deployed is not working
