### ISSUE TITLE
build fails on certain versions of osx due to avx-512 instructions

### ISSUE THREAD

**Issue by Hardcore-fs** [Chia-Network/chiavdf#83]
The build chain "assumes" that avx-512 instructions can be assembled, even if they cannot be executed.

However on certain versions of osx   the build tools do not even have the AVX-512 instructions available.

There should be an option / flag to completely block the  source files from being evaluated, to prevent it erroring on some versions of xcode.

`  [100%] Linking CXX shared module build/lib.macosx-10.9-x86_64-3.9/chiavdf.cpython-39-darwin.so
  [100%] Built target chiavdf
  running build_hook
  avx512_asm_compiled.s:4:14: error: instruction requires: AVX-512 ISA
  avx512_Xx_4: VPBROADCASTQ ZMM4, RDI      # to_avx512_integer:254    VPBROADCASTQ `in_num_limbs_vector, `in_num_limbs
               ^
  avx512_asm_compiled.s:5:14: error: instruction requires: AVX-512 ISA
  avx512_Xx_5: VPABSQ ZMM4, ZMM4           # to_avx512_integer:255    VPABSQ `in_num_limbs_vector, `in_num_limbs_vector
               ^
  avx512_asm_compiled.s:20:15: error: instruction requires: AVX-512 ISA
  avx512_Xx_20: VPCMPUQ k1, ZMM4, ZMMWORD PTR [RIP+_avx512_label_0], 6 # to_avx512_integer:268    VPCMPUQ k1, `in_num_limbs_vector, ZMMWORD PTR [RIP+_avx512_label_0], 6
                ^
  avx512_asm_compiled.s:21:30: error: unexpected token in argument list
  avx512_Xx_21: VMOVDQU64 ZMM0 {k1}{z}, [RSI+0] # to_avx512_integer:271    VMOVDQU64 `input_registers_0 {k1}{z}, [`in_data+0]
                               ^
  avx512_asm_compiled.s:34:15: error: instruction requires: AVX-512 ISA
  avx512_Xx_34: VPCMPUQ k1, ZMM4, ZMMWORD PTR [RIP+_avx512_label_1], 6 # to_avx512_integer:268    VPCMPUQ k1, `in_num_limbs_vector, ZMMWORD PTR [RIP+_avx512_label_1], 6
                ^
  avx512_asm_compiled.s:35:30: error: unexpected token in argument list
  avx512_Xx_35: VMOVDQU64 ZMM1 {k1}{z}, [RSI+64] # to_avx512_integer:271    VMOVDQU64 `input_registers_1 {k1}{z}, [`in_data+64]
`

**Comment by hoffmang9** [comment]
Are you intending to build a timelord? The README shows how to build only the chiavdf library which is generally all you need for most uses.

**Comment by hoffmang9** [comment]
Are you intending to build a timelord? The README shows how to build only the chiavdf library which is generally all you need for most uses.

**Comment by Hardcore-fs** [comment]
Ahhhh......
I thought it was part of the default install....
since walking thru this  and following each step got me the failure.

https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL

it looks like it builds everything.... even if I might not need it.
that might be a huge time saver.......

**Comment by Hardcore-fs** [comment]
after a second look
and doing this:
BUILD_VDF_CLIENT = os.getenv("BUILD_VDF_CLIENT", "Y") == "N"
BUILD_VDF_BENCH = os.getenv("BUILD_VDF_BENCH", "N") == "N"

it still errors

**Comment by emlowe** [comment]
Closing - this is apparently only a problem on macOS 10.13 High Sierra which is not supported and will not work due to other dependencies (gulrak)
